using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WeddingManagementSystem
{
    class UserAction : IActionSaveUpdate
    {
        public int Create(PostUserDTO post)
        {
            UserRegistration entityUser = new UserRegistration();

            #region :: DTO Properties they come from browser :: Customer
            entityUser.FirstName = post.FirstName;
            entityUser.MiddleName = post.MiddleName;
            entityUser.LastName = post.LastName;
            entityUser.Gender = post.Gender;
            entityUser.UserName = post.UserName;
            entityUser.Password = post.Password;
            entityUser.Number = post.Number;
            entityUser.Address = post.Address;
            #endregion

            #region :: Auto Generated by Server :: BY CODE by DEveloper
            entityUser.CreatedBy = 1;
            entityUser.CreatedOn = DateTime.Now;
            entityUser.IsDeleted = false;
            #endregion




            return 0; 
        }
        public int Update(PutUserDTO put) 
        {
            UserRegistration obj = new UserRegistration();
            obj.UserID = put.UserID;
            obj.FirstName =  put.FirstName;
            obj.MiddleName = put.MiddleName;
            obj.LastName =   put.LastName;
            obj.Gender =     put.Gender;
            obj.UserName =   put.UserName;
            obj.Password =   put.Password;
            obj.Number =     put.Number;
            obj.Address =    put.Address;
            return 0;
        }
    }
}
